name = "RheaMetacycParser"
uuid = "5dc06827-e3ab-462e-b239-654b0cf09987"
authors = ["HettieC <hester.chapman@btinternet.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
