name = "RheaMetacycParser"
uuid = "5dc06827-e3ab-462e-b239-654b0cf09987"
authors = ["HettieC <hester.chapman@btinternet.com> and contributors"]
version = "0.1.0"

[deps]
COBREXA = "babc4406-5200-4a30-9033-bf5ae714c842"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
ReadableRegex = "cbbcb084-453d-4c4c-b292-e315607ba6a4"

[compat]
julia = "1"
COBREXA = "1.4"
DocStringExtensions = "0.9"
ReadableRegex = "0.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
